LOAD DATA LOCAL INFILE '~/twitter/q5/part-00000'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00001'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00002'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00003'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00004'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00005'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00006'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00007'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00008'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00009'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00010'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00011'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00012'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00013'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00014'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00015'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q5/part-00016'
INTO TABLE timeplace_q5
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';