LOAD DATA LOCAL INFILE '~/twitter/q2datahbase1'
INTO TABLE tweets_q2 
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q2datahbase2'
INTO TABLE tweets_q2 
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q2datahbase3'
INTO TABLE tweets_q2 
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q2datahbase4'
INTO TABLE tweets_q2 
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q2datahbase5'
INTO TABLE tweets_q2
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q2datahbase6'
INTO TABLE tweets_q2
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q2datahbase7'
INTO TABLE tweets_q2
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q2datahbase8'
INTO TABLE tweets_q2
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '~/twitter/q2datahbase9'
INTO TABLE tweets_q2
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n';
